universe/catalog/urls.py
from django.urls import include, path, re_path
from . import views




urlpatterns = [
    re_path(r'^$', views.index, name='index'),
    re_path(r'^book/$', views.BookListView.as_view(), name='books'),
    re_path(r'^book/(?P<pk>\d+)$', views.BookDetailView.as_view(), name='books-detail'),
    re_path(r'^author/(?P<pk>\d+)$', views.AuthorDetailView.as_view(), name='author-detail'),
    re_path(r'^test/$', views.test, name='test'),
    re_path(r'^author/$', views.AuthorListView.as_view(), name='authors'),
]


urlpatterns += [
    re_path('accounts/', include('django.contrib.auth.urls')),
]

universe/lobby/urls.py
from django.urls import path
from . import views


urlpatterns = [
    path('', views.index, name='index'),
]

universe/polls/urls.py
from django.urls import path
from . import views

app_name = 'polls'
urlpatterns = [
    path('', views.index, name='index'),
    path('<int:question_id>/', views.detail, name='detail'),
    path('<int:question_id>/results', views.results, name='results'),
    path('<int:question_id>/vote', views.vote, name='vote'),

]

universe/universe/urls.py
from django.contrib import admin
from django.urls import path, include
import re

urlpatterns = [
    path('', include('catalog.urls')),
    path('admin/', admin.site.urls),
]

urlpatterns += [
    path('catalog/', include('catalog.urls')),
]

universe/catalog/models.py
from django.db import models
from django.urls import reverse


class Genre(models.Model):
    """
    Description
    """
    #  Fields

    name = models.CharField(max_length=200, help_text='Enter a book genre')

    def __str__(self):
        return self.name


class Book(models.Model):
    """
    Description
    """
    #  Fields

    title = models.CharField(max_length=200, help_text='Enter a book name')
    author = models.ForeignKey('Author', on_delete=models.SET_NULL, null=True)
    summary = models.TextField(max_length=1000, help_text='Enter a brief description')
    isbn = models.CharField('ISBN', max_length=13, help_text='13character')
    genre = models.ManyToManyField(Genre, help_text='Select a genre')

    #  Metadata
    # class Meta:
    #     ordering = ['-field_name']

    # Methods

    def get_absolute_url(self):
        """
        Returns url
        """
        return reverse('books-detail', args=[str(self.id)])

    def __str__(self):
        return self.title


class Author(models.Model):
    """
    Description
    """
    #  Fields

    first_name = models.CharField(max_length=100)
    last_name = models.CharField(max_length=100)
    date_to_birth = models.DateField(null=True, blank=True)
    date_to_death = models.DateField('Died', null=True, blank=True)
    biography = models.TextField(null=True, blank=True)

    #  Metadata
    # class Meta:
    #     ordering = ['-field_name']

    # Methods

    def get_absolute_url(self):
        """
        Returns url
        """
        return reverse('author-detail', args=[str(self.id)])

    def __str__(self):
        return f'{self.last_name}, {self.first_name}'

universe/lobby/models.py
from django.db import models


class Question(models.Model):
    question_text = models.CharField(max_length=200)
    pub_date = models.DateTimeField('date published')

universe/polls/models.py
from django.db import models
import datetime
from django.utils import timezone


class Question(models.Model):
    question_text = models.CharField(max_length=200)
    pub_date = models.DateTimeField('date published')

    def __str__(self):
        return self.question_text

    def was_published_recently(self):
        return self.pub_date >= timezone.now() - datetime.timedelta(days=1)


class Choice(models.Model):
    question = models.ForeignKey(Question, on_delete=models.CASCADE)
    choice_text = models.CharField(max_length=200)
    votes = models.IntegerField(default=0)

    def __str__(self):
        return self.choice_text

universe/catalog/views.py
from django.shortcuts import get_object_or_404, render
from django.views import generic
from .models import Book, Author, Genre
from django.contrib.auth.decorators import login_required
from django import forms


@login_required()
def test(request):
    return render(request, 'catalog/test.html')


def index(request):
    """

    :param request:
    :return:
    """

    num_books = Book.objects.all().count()
    num_authors = Author.objects.count()
    num_visits = request.session.get('num_visits', 0)
    request.session['num_visits'] = num_visits+1

    return render(
        request,
        'catalog/index.html',
        context=
        {
            'num_books': num_books, 'num_authors': num_authors, 'num_visits': num_visits,
        },
    )


class BookListView(generic.ListView):
    model = Book

    # def get_queryset(self):
    #     return Book.objects.filter(title_contains='war')[:5]


class BookDetailView(generic.DetailView):
    model = Book


class AuthorListView(generic.ListView):
    model = Author


class AuthorDetailView(generic.DetailView):
    model = Author

universe/lobby/views.py
from django.shortcuts import render
from django.http import HttpResponse
# Create your views here.


def index(request):
    return HttpResponse('Hello, world. You are at the universe index!')

universe/polls/views.py
from django.shortcuts import get_object_or_404, render
from django.http import HttpResponse, Http404
from .models import Question
from django.template import loader


def index(request):
    latest_question_list = Question.objects.order_by('pub_date')[:5]
    # template = loader.get_template('polls/index.html')
    context = {
        'latest_question_list': latest_question_list
    }
    return render(request, 'polls/index.html', context)


def detail(request, question_id):

    question = get_object_or_404(Question, pk=question_id)
    return render(request, 'polls/detail.html', {'question': question})


def results(request, question_id):
    response = f"You're looking at the results of question {question_id}"
    return HttpResponse(response)


def vote(request, question_id):
    return HttpResponse(f"You're voting on question {question_id}")

universe/catalog/templates/catalog/author_detail.html
{% extends 'catalog/base_generic.html' %}

{% block content %}
<h1>Title: {{ author.last_name }}</h1>

<p>Name: {{ author.first_name }} {{ author.last_name }}</p>
<p>Biography: {{ author.biography }}</p>


{% endblock content %}

universe/catalog/templates/catalog/author_list.html
{% extends 'catalog/base_generic.html' %}

{% block content %}

<h1>Authors list</h1>

{% if author_list %}
<ul>
    {% for author in author_list %}
    <li><a href="{{ author.get_absolute_url }}">{{ author.first_name }} {{ author.last_name }}</a></li>
    {% endfor %}

</ul>
{% else %}
<p>There id no books here</p>
{% endif %}


{% endblock content %}

universe/catalog/templates/catalog/base_generic.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    {% block title %}<title>Домашняя библиотека</title>{% endblock title %}

  {% load static %}
  <link rel="stylesheet" href="{% static 'css/styles.css' %}">
</head>
<body>
<div class="container">

  {% block sidebar %}
      <ul>
        <li><a href="{% url 'index' %}">Домой</a></li>
        <li><a href="{% url 'authors' %}">Авторы</a></li>
        <li><a href="{% url 'books' %}">Книги</a></li>
          {% if user.is_authenticated %}
          <li>Вы вошли как: {{ user.get_username }}</li>
          <li><a href="{% url 'logout' %}?next={{ request.path }}">Выйти</a></li>
          {% else %}
          <li><a href="{% url 'login' %}?next={{ request.path }}">Войти</a></li>
          {% endif %}
      </ul>
  {% endblock sidebar %}
  <div>
  {% block content %}
  {% endblock content %}
  </div>
</div>
</body>
</html>

universe/catalog/templates/catalog/book_detail.html
{% extends 'catalog/base_generic.html' %}

{% block content %}
<h1>Title: {{ book.title }}</h1>

<p><strong>Summary: </strong> {{ book.summary }}</p>
<p><strong>ISBN: </strong>{{ book.isbn }}</p>


{% endblock content %}

universe/catalog/templates/catalog/book_list.html
{% extends 'catalog/base_generic.html' %}

{% block content %}

<h1>Book list</h1>

{% if book_list %}
<ul>
    {% for book in book_list %}
    <li><a href="{{ book.get_absolute_url }}">{{ book.title }}</a>
    ({{ book.author }})</li>
    {% endfor %}

</ul>
{% else %}
<p>There id no books here</p>
{% endif %}


{% endblock content %}

universe/catalog/templates/catalog/index.html
{% extends 'catalog/base_generic.html' %}

{% block content %}
<h1>Домашнаяя библиотека</h1>

<p>Это моя личная бибилиотека, в которую я сохраняю прочтенные книги.
    Эти книги доступны для ознакомительного просмотра, однако загружать их не разрешается,
в виду отсутствия договоренности с авторами.</p>

<h2>Динамический контент</h2>

<p>Библиотека содержит: </p>
<ul>
    <li><strong>Книг: </strong>{{ num_books }}</li>
    <li><strong>Авторов: </strong>{{ num_authors }}</li>
    <li><strong>Посещений: </strong>{{ num_visits }}</li>
</ul>
{% endblock content %}

universe/catalog/templates/catalog/test.html
{% extends 'catalog/base_generic.html' %}

{% block content %}
<h1>OKAY!</h1>


{% endblock content %}

universe/polls/templates/polls/detail.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>

<form action="{% url 'polls:vote' question.id %}" method="post">
    {% csrf_token %}
    <fieldset>
        <legend><h1>{{ question.question_text }}</h1></legend>
        {% if error_message %} <p><strong>{{ error_message }}</strong></p>{% endif %}
        {% for choice in question.choice_set.all %}
    </fieldset>
</form>



    <h1>{{ question.question_text }}</h1>
    <ul>
        {% for choice in question.choice_set.all %}
        <li>{{ choice.choice_text }}</li>
        {% endfor %}
    </ul>





</body>
</html>

universe/polls/templates/polls/index.html
<!doctype html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Document</title>
</head>
<body>
    {% if latest_question_list %}
<ul>
    {% for question in latest_question_list %}
    <li><a href="{% url 'polls:detail' question.id %}">{{ question.question_text }}</a></li>
    {% endfor %}
</ul>
{% else %}
<p>No polls are available</p>
{% endif %}
</body>
</html>